trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@1
  displayName: Build Docker Compose services
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Managed Identity' # Service connection for ACR authentication
    dockerComposeFile: 'docker-compose.yml' # Path to your docker-compose.yml
    action: 'Build services'
    dockerComposeFileArgs: |
      BUILD_ID=$(Build.BuildId)
    additionalImageTags: |
      develop
      $(Build.BuildId)
    projectName: 'masapp' # Base name for images (e.g., masapp/service-name)

- task: DockerCompose@1
  displayName: Push Docker Compose services to ACR
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Managed Identity'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Push services'
    dockerComposeFileArgs: |
      BUILD_ID=$(Build.BuildId)
    additionalImageTags: |
      develop
      $(Build.BuildId)
    projectName: 'masapp'

- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Managed Identity'
    acrName: 'mascontainers'
    imageToDeploy: 'mascontainers.azurecr.io/masapp/web:$(Build.BuildId)' # Adjust to specific service name
    containerAppName: 'masapp-dev'
    resourceGroup: 'MAS-APP-RG'
    containerAppEnvironment: 'mas-app-dev-env'